# Generated by Django 3.2.9 on 2021-11-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='percentage_split',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='requested_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='finance.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('s', 'SUCCESSFUL'), ('f', 'FAILED')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('c', 'CREDIT'), ('d', 'DEBIT')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='finance.account'),
        ),
    ]
