# Generated by Django 3.2.9 on 2021-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20211126_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('s', 'SUCCESSFUL'), ('p', 'PENDING')], max_length=15),
        ),
    ]
