# Generated by Django 3.2.9 on 2021-11-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20211127_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='percentage_split',
        ),
    ]
